name: Update Weather RSS

# ① 触发方式：手动 + 定时
on:
  workflow_dispatch:              # 在 Actions 页可手动点击
  schedule:
    # └─ UTC 时间；此处例子 = 台北时间每日 07:00
    - cron: '0 0 * * *'

permissions:
  contents: write                 # 允许推送代码

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1) 拉代码
    - uses: actions/checkout@v4
      with:
        ref: main                 # 若默认分支不是 main，请改成相应分支

    # 2) Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'    # 与本地一致即可

    # 3) 安装依赖（如果有 requirements.txt）
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4) 运行脚本生成 RSS
    - name: Run weather script
      env:
        CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
        BARK_KEY:   ${{ secrets.BARK_KEY }}      # 可选
        RSS_LINK:  'https://eliu-lotso.github.io/weather-rss/weather.xml'
        DEBUG_API_RAW: '1'
      run: |
        python main.py

    # 5) 如有变动则提交并推送
    - name: Commit & push if changed
      run: |
        git config user.name  github-actions
        git config user.email github-actions@users.noreply.github.com
        if [ -n "$(git status --porcelain docs/weather.xml)" ]; then
          git add docs/weather.xml
          git commit -m "Auto update weather RSS $(date -u '+%F %T')"
          git push
        else
          echo "No RSS change → skip commit."
        fi